config/routes.rb
BeerServer::Application.routes.draw do
  apipie

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  namespace :api do
    scope 'my' do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: [:show, :update]
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followings, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :followers, only: :index
    end

    resources :users, only: :index do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: :show
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followers, only: :index
      resources :followings, only: :index
    end

    resources :events, only: [] do
      resources :likes, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :comments, only: [:index, :create, :destroy]
    end

    resources :checks, only: :create
    resources :beers, only: [:index, :create]
    resources :journal_entries, only: :index
  end

  namespace :admin do
    resources :beers do
      put :accept, on: :member
      put :reject, on: :member
    end
    resources :badges
    resources :users
    resources :events, only: :index

    root to: 'beers#index'
  end

  resources :users, only: [:index, :show]

  # if Rails.env.development?
  #   mount MailView => 'mail_view'
  # end

  root to: 'home#index'
end

app/models/badge.rb
# == Schema Information
#
# Table name: badges
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  badge_type     :string(255)
#  condition      :text
#  quantity       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  description_fr :text
#  photo          :string(255)
#  published      :boolean
#  description_en :text
#

class Badge < ActiveRecord::Base
  has_many :awards, dependent: :destroy
  has_many :users, through: :awards

  validates :condition, presence: true

  mount_uploader :photo, BadgePhotoUploader

  scope :ordered, -> { order('created_at DESC') }
  scope :published, -> { where('published IS TRUE') }

  def description(locale = I18n.default_locale)
    if I18n.available_locales.include?(locale)
      send("description_#{locale}")
    else
      send("description_#{I18n.default_locale}")
    end
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::ApplicationController
  before_filter :badge_params, only: %i(create update)
  load_and_authorize_resource

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new badge_params
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update_attributes badge_params
      redirect_to admin_badges_path
    else
      render :edit, status: 422
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit!
  end
end

app/views/admin/badges/_form.html.haml
- badge = f.object

%fieldset
  %legend New Badge

  .row
    .large-6.columns
      = f.input :photo
    .large-6.columns
      = image_tag badge.photo.thumb.url, size: '100x100'
  .row
    .large-6.columns
      = f.input :name
    .large-6.columns
      = f.input :badge_type
  .row
    .large-3.columns
      = f.input :description_fr
    .large-3.columns
      = f.input :description_en
    .large-6.columns
      = f.input :condition
  .row
    .large-6.columns
      = f.input :quantity
    .large-6.columns
      = f.input :published, wrapper: 'foundation'

  = f.button :submit

app/views/admin/badges/edit.html.haml
.row
  = link_to 'Back', admin_badges_path, class: 'button'

.row
  = simple_form_for @badge, url: admin_badge_path(@badge) do |f|
    = render partial: 'form', locals: {f: f}

app/views/admin/badges/index.html.haml
.row
  .large-12.columns
    = link_to 'New Badge', new_admin_badge_path, class: 'button'

.row
  .large-12.columns
    %table.large-12.columns.responsive
      %thead
        %tr
          - %w(photo name bage_type description_fr description_en conditon created_at published actions).each do |th|
            %th= th

      %tbody
        - @badges.each do |badge|
          %tr
            %td= image_tag badge.photo.thumb.url, size: '100x100'
            %td= badge.name
            %td= badge.badge_type
            %td= badge.description_fr
            %td= badge.description_en
            %td= badge.condition
            %td= badge.created_at
            %td= badge.published
            %td
              = link_to 'Edit', edit_admin_badge_path(badge), class: 'button success small'
              = link_to 'Delete', admin_badge_path(badge), method: :delete, data: {confirm: 'Are you sure?'}, class: 'button alert small'

app/views/admin/badges/new.html.haml
.row
  = link_to 'Back', admin_badges_path, class: 'button'

.row
  = simple_form_for @badge, url: admin_badges_path do |f|
    = render partial: 'form', locals: {f: f}