config/routes.rb
BeerServer::Application.routes.draw do
  apipie

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  namespace :api do
    scope 'my' do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: [:show, :update]
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followings, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :followers, only: :index
    end

    resources :users, only: :index do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: :show
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followers, only: :index
      resources :followings, only: :index
    end

    resources :events, only: [] do
      resources :likes, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :comments, only: [:index, :create, :destroy]
    end

    resources :checks, only: :create
    resources :beers, only: [:index, :create]
    resources :journal_entries, only: :index
  end

  namespace :admin do
    resources :beers do
      put :accept, on: :member
      put :reject, on: :member
    end
    resources :badges
    resources :users
    resources :events, only: :index

    root to: 'beers#index'
  end

  resources :users, only: [:index, :show]

  # if Rails.env.development?
  #   mount MailView => 'mail_view'
  # end

  root to: 'home#index'
end

app/models/beer.rb
# == Schema Information
#
# Table name: beers
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  country          :string(255)
#  beer_color_id    :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  accepted         :boolean
#  added_by_id      :integer
#  font_color       :string(255)
#  background_color :string(255)
#  brewery_id       :integer
#

class Beer < ActiveRecord::Base
  include Searchable::Models
  include Loggable

  COLOR_POOL = [
    ['#000000', '#ffffff'],
    ['#00C57D', '#ffffff'],
    ['#FF5800', '#ffffff'],
    ['#FF9C00', '#ffffff'],
    ['#FF4233', '#ffffff'],
    ['#0089C6', '#ffffff'],
  ]

  searchable_by :name

  after_create :assign_color

  belongs_to :beer_color
  belongs_to :brewery
  belongs_to :added_by, class_name: 'User'
  has_many :checks, dependent: :destroy
  has_many :users, through: :checks

  default_scope -> { includes(:beer_color) }

  scope :ordered, -> do
    select('beers.id, beers.name, beers.beer_color_id, COUNT(DISTINCT(checks.id)) AS checks_count')
    .joins(:checks).order('checks_count DESC').group("beers.id")
  end

  scope :with_color, -> { includes(:beer_color, :added_by) }
  scope :suggested, -> { where('accepted IS NULL').with_color }
  scope :accepted, -> { where('accepted IS TRUE').with_color }
  scope :rejected, -> { where('accepted IS FALSE').with_color }

  delegate :name, to: :beer_color, prefix: true, allow_nil: true

  validates :name, presence: true

  def should_be_logged?
    self.accepted
  end

  def assign_color
    random_pattern = COLOR_POOL[rand(COLOR_POOL.length)]
    self.update_column :background_color, random_pattern[0]
    self.update_column :font_color, random_pattern[1]
  end
end

app/controllers/admin/beers_controller.rb
class Admin::BeersController < Admin::ApplicationController
  load_and_authorize_resource

  def index
    @beers = Beer.accepted
    @suggested = Beer.suggested
    @rejected = Beer.rejected
  end

  def new
    @beer = Beer.new
  end

  def create
    @beer = Beer.new(beer_params).tap do |beer|
      beer.accepted = true
      beer.added_by = current_user
    end
    if @beer.save
      redirect_to admin_beers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @beer.update_attributes beer_params
      redirect_to admin_beers_path
    else
      render :edit
    end
  end

  def accept
    @beer.accepted = true
    @beer.save
    NotificationMailer.accepted_beer(@beer).deliver
    redirect_to admin_beers_path
  end

  def reject
    @beer.accepted = false
    @beer.save
    redirect_to admin_beers_path
  end

  def destroy
    @beer.destroy
    redirect_to admin_beers_path
  end

  private

  def beer_params
    params.require(:beer).permit!
  end
end

app/controllers/api/beers_controller.rb
class Api::BeersController < Api::ApplicationController
  resource_description do
    short 'Beer related endpoints'
    formats ['json']
    error 500, "Server crashed for some reason"
  end

  include SearchableMethods

  can_search_for :beers

  api :GET, '/beers/', 'List all beers'
  param :page, :number, desc: 'The page index'
  description 'This endpoint returns the list of beers'
  def index
    @beers = @beers.accepted
    render json: @beers
  end

  api :POST, "/beers", "Create a beer"
  param :beer, Hash do
    param :name, String
  end
  def create
    begin
      @beer = current_user.created_beers.create(beer_params)
      NotificationMailer.new_beer(@beer).deliver
      render json: @beer
    rescue ActionController::ParameterMissing
      render json: {error: "Error"}
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name)
  end

end

app/views/admin/beers/_form.html.haml
- beer = f.object

%fieldset
  %legend New Beer
  .row
    .large-6.columns
      = f.input :name, wrapper: :foundation
    .large-3.columns
      = f.input :background_color, wrapper: :foundation
    .large-3.columns
      = f.input :font_color, wrapper: :foundation
  .row
    .large-6.columns
      = f.association :beer_color
    .large-6.columns
      = f.input :country, as: :string

  = f.submit class: 'button'

app/views/admin/beers/_list.html.haml
%table.large-12.columns.responsive
  %thead
    %tr
      - %w(name beer_color country created_at added_by actions).each do |th|
        %th= th

  %tbody
    - collection.each do |beer|
      %tr
        %td= beer.name
        %td= beer.beer_color_name
        %td= beer.country
        %td= beer.created_at
        %td
          - if beer.added_by
            = beer.added_by.nickname
        %td
          = yield beer

app/views/admin/beers/edit.html.haml
.row
  = link_to 'Back', admin_beers_path, class: 'button'

.row
  = simple_form_for @beer, url: admin_beer_path(@beer) do |f|
    = render partial: 'form', locals: {f: f}

app/views/admin/beers/index.html.haml
.row
  .large-12.columns
    = link_to 'New Beer', new_admin_beer_path, class: 'button'

.row
  .large-12.columns
    %h2= 'Suggestions'
    - if @suggested.any?
      = render layout: 'list', locals: { collection: @suggested } do |beer|
        = link_to 'Accept', accept_admin_beer_path(beer), method: :put, class: 'small success button'
        = link_to 'Edit', edit_admin_beer_path(beer), class: 'small button'
        = link_to 'Delete', admin_beer_path(beer), method: :delete, data: {confirm: 'Are you sure?'}, class: 'small alert button'
    - else
      = "No suggestions"



.row
  .large-12.columns
    %h2= "All beers (#{Beer.accepted.count})"
    - if @beers.any?
      = render layout: 'list', locals: { collection: @beers } do |beer|
        = link_to 'Reject', reject_admin_beer_path(beer), method: :put, class: 'small success button'
        = link_to 'Edit', edit_admin_beer_path(beer), class: 'small button'
        = link_to 'Delete', admin_beer_path(beer), method: :delete, data: {confirm: 'Are you sure?'}, class: 'small alert button'
    - else
      = "No beers"

.row
  .large-12.columns
    %h2= 'Rejected beers'
    - if @rejected.any?

      = render layout: 'list', locals: { collection: @rejected } do |beer|
        = link_to 'Re accept', accept_admin_beer_path(beer), method: :put, class: 'small success button'
        = link_to 'Edit', edit_admin_beer_path(beer), class: 'small button'
        = link_to 'Delete', admin_beer_path(beer), method: :delete, data: {confirm: 'Are you sure?'}, class: 'small alert button'

    - else
      = "No beers"

app/views/admin/beers/new.html.haml
.row
  = link_to 'Back', admin_beers_path, class: 'button'

.row
  = simple_form_for @beer, url: admin_beers_path do |f|
    = render partial: 'form', locals: {f: f}