config/routes.rb
BeerServer::Application.routes.draw do
  apipie

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  namespace :api do
    scope 'my' do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: [:show, :update]
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followings, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :followers, only: :index
    end

    resources :users, only: :index do
      resources :feed, only: :index
      resources :notifications, only: :index
      resource :profile, only: :show
      resources :beers, only: :index, controller: 'my_beers'
      resources :badges, only: :index, controller: 'my_badges'
      resources :followers, only: :index
      resources :followings, only: :index
    end

    resources :events, only: [] do
      resources :likes, only: [:index, :create] do
        delete :destroy, on: :collection
      end
      resources :comments, only: [:index, :create, :destroy]
    end

    resources :checks, only: :create
    resources :beers, only: [:index, :create]
    resources :journal_entries, only: :index
  end

  namespace :admin do
    resources :beers do
      put :accept, on: :member
      put :reject, on: :member
    end
    resources :badges
    resources :users
    resources :events, only: :index

    root to: 'beers#index'
  end

  resources :users, only: [:index, :show]

  # if Rails.env.development?
  #   mount MailView => 'mail_view'
  # end

  root to: 'home#index'
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title BeechApp
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "admin", "data-turbolinks-track" => true
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tags
  %body.antialiased
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1
            %a{href: "#"} Beech Admin
        %li.toggle-topbar.menu-icon
          %a{href: "#"}
            %span
      %section.top-bar-section
        %ul.left
          %li.divider
          %li.active
            = link_to 'Beers', admin_beers_path
          %li.divider
          %li
            = link_to 'Badges', admin_badges_path
          %li.divider
          %li
            = link_to 'Users', admin_users_path
          %li.divider
          %li
            = link_to 'Events', admin_events_path

        %ul.right
          %li.divider
          %li.has-form
            %form
              .row.collapse
                .small-8.columns
                  %input(type="text")

                .small-4.columns
                  %a(href="#" class="alert button")Search
          %li.divider.show-for-small
          %li.has-dropdown
            %a{:href => "#"}= current_user.nickname
            %ul.dropdown
              %li= link_to 'Logout', destroy_user_session_path, method: 'delete', data: {confirm: 'Are you sure?'}

    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BeechApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0", name: "viewport"}
  %body
    - if user_signed_in?
      .links
        = link_to 'Se déconnecter', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}
    = yield

app/views/layouts/errors.html.haml
!!!
!= cc_html class: 'no-js' do
  %head
    %title BeerServer
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/notification_mailer.html.haml
%table{style: 'border: 1px solid rgb(231,231,231); border-spacing: 0; font-family: Helvetica neue, Helvetica, Arial; padding-bottom: 20px;'}
  %thead
    %th{style: 'padding: 0;'}= image_tag('/mail_header.gif')

  %tbody{style: 'color: #666; padding: 10px;'}
    = yield

    %tr
      %td{style: 'color: black; padding: 10px;'}
        See you soon. Keep on beeching
    %tr
      %td{style: 'color: black; padding: 10px; text-align: center;'}
        = link_to 'Follow us on twitter', 'https://twitter.com/getbeech', style: 'background-color: rgb(240,123,48); padding: 10px; margin-bottom: 20px; color: white; font-weight: bold; text-decoration: none; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px;'